org: aljeshishe3
app: aws-python-scheduled-cron-project
service: crawler-front
useDotenv: true
frameworkVersion: '3'

custom:
  s3_bucket: "${self:app}-data-bucket-${self:provider.stage}"
  pythonRequirements:
    # dockerizePip: true
    usePoetry: true
    # layer: true

provider:
  name: aws
  runtime: python3.9
  stage: ${opt:stage, env:AWS_STAGE, 'dev'}
  region: ${opt:region, env:AWS_REGION, 'eu-central-1'}
  memorySize: 1024

functions:
  app:
    handler: app.endpoint
    events:
      - httpApi:
          path: /
          method: get


package:
  exclude:
    - node_modules/**
    - .venv/**


plugins:
  - serverless-python-requirements
  - serverless-offline
