app: crawler
org: aljeshishe3
service: front
useDotenv: true

frameworkVersion: '3'

custom:
  wsgi:
    app: app.server
    packRequirements: false

provider:
  name: aws
  runtime: python3.9
  stage: ${opt:stage, env:AWS_STAGE, 'dev'}
  region: ${opt:region, env:AWS_REGION, 'eu-central-1'}
  deploymentMethod: direct

functions:
  api:
    events:
      - httpApi: '*'
    image: ${env:REMOTE_IMAGE}

plugins:
  - serverless-wsgi
  - serverless-offline

