app: ${self:parent.app}
org: ${self:parent.org}
service: front
useDotenv: true
frameworkVersion: ${self:parent.frameworkVersion}

parent: ${file(../serverless.common.yml):parent}

# TODO GARCHEV temporary comment, because wsgi removed wsgi_handler.py and
#custom:
#  wsgi:
#    app: app.server
#    packRequirements: false

provider:
  name: aws
  runtime: python3.9
  stage: ${self:parent.stage}
  region: ${self:parent.region}
  deploymentMethod: direct
  stackName: ${self:parent.full_service_name}-stack
  deploymentPrefix: ${self:parent.deploymentPrefix}

  tags:
    key: tagGrachev
  stackTags:
    key: stackTagGrachev

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:*"
          Resource: "*"
  ecr:
    images:
      latest:
        uri: ${self:parent.REMOTE_IMAGE}

functions:
  func:
    name: ${self:parent.full_service_name}-func
    events:
      - httpApi: '*'
    image: latest
    environment:
      AWS_S3_BUCKET: ${self:parent.AWS_S3_BUCKET}


plugins:
  - serverless-offline

