app: crawler
org: aljeshishe3
service: worker
useDotenv: true
frameworkVersion: '3'

custom:
  s3_bucket: ${file(../serverless.common.yml):custom.s3_bucket}
  pythonRequirements:
    dockerizePip: true
    usePoetry: true
    layer: true

provider:
  name: aws
  runtime: python3.9
  stage: ${opt:stage, env:AWS_STAGE, 'dev'}
  region: ${opt:region, env:AWS_REGION, 'eu-central-1'}
  timeout: 900
  memorySize: 1024
  deploymentMethod: direct
#  iam:
#    role:
#      statements:
#        - Effect: "Allow"
#          Action:
#            - "s3:*"
#          Resource: "*"

package:
  exclude:
    - node_modules/**
    - .venv/**

functions:
  cronHandler:
    handler: handler.run
    events:
      - schedule: cron(0 12 * * ? *)
    environment:
        AWS_S3_BUCKET: ${self:custom.s3_bucket}

    layers:
      - Ref: PythonRequirementsLambdaLayer

plugins:
  - serverless-python-requirements
