[tool.poetry]
<<<<<<< HEAD
name = "worker"
=======
name = "collector"
>>>>>>> parent of 1ebe772 (dashboards: removed poetry.lock pyproject.toml requirements.txt)
version = "0.1.0"
description = ""
authors = ["alexeygrachev <agrachev@cindicator.com>"]
readme = "README.md"

[tool.poetry.dependencies]
<<<<<<< HEAD
python = "^3.7"
=======
python = "^3.8"
>>>>>>> parent of 1ebe772 (dashboards: removed poetry.lock pyproject.toml requirements.txt)
requests = "^2.28.1"
pandas = "^1.5.2"
boto3 = "^1.26.16"
pyaml = "^21.10.1"
munch = "^2.5.0"
<<<<<<< HEAD


[tool.poetry.group.dev.dependencies]
jupyter = "^1.0.0"
common = {path="../common"}
=======
python-dotenv = "^0.21.0"
jsonpath-ng = "^1.5.3"
loguru = "^0.6.0"
sentry-sdk = "^1.15.0"

[tool.poetry.group.dev.dependencies]
jupyter = "^1.0.0"
pytest = "^7.2.1"
common = {path = "../common"}
>>>>>>> parent of 1ebe772 (dashboards: removed poetry.lock pyproject.toml requirements.txt)

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
